### ISSUE TITLE
Problem with phploc and phpcpd

### ISSUE THREAD

**Issue by pyvm** [sebastianbergmann/finder-facade#13]
Hi ,
Its impossible to use `phpcpd` with `phploc` in the same pipeline because `phpcpd` need finder-face 2
but `phploc` want stability version of finder-face

**Comment by sebastianbergmann** [comment]
See https://github.com/sebastianbergmann/phploc/issues/202#issuecomment-566398879 and https://github.com/sebastianbergmann/phpcpd/issues/177#issuecomment-566398886.
